export default {
	"#gz_jiangqing:die": "竟……破我阵法……",
	"#gz_zhonghui:die": "吾机关算尽，却还是棋错一着……",
	"#gzzhaoxin1": "行明动正，何惧他人讥毁。",
	"#gzzhaoxin2": "大业之举，岂因宵小而动？",
	"#gzsuzhi1": "敌军势大与否，无碍我自计定施。",
	"#gzsuzhi2": "汝竭力强攻，也只是徒燥军心。",
	"#gzfankui1": "胆敢诽谤惑众，这就是下场！",
	"#gzfankui2": "今天，就拿你来杀鸡儆猴。",
	"#gz_simazhao:die": "千里之功，只差一步了……",
	"#gzhuaiyi1": "曹魏可王，吾亦可王！",
	"#gzhuaiyi2": "这天下，本就是我囊中之物。",
	"#gzzisui1": "仲达公，敢问这辽隧之战，谁胜谁负啊，哈哈哈哈……",
	"#gzzisui2": "凡从我大燕者，授印封爵，全族俱荣！",
	"#gz_gongsunyuan:die": "流星骤损，三军皆溃，看来大势去矣……",
	"#gzxingzhao1": "让我先探他一探。",
	"#gzxingzhao2": "船，也不是一天就能造出来的。",
	"#gzxingzhao_xunxun1": "拿些上好的木料来。",
	"#gzxingzhao_xunxun2": "精挑细选，方能成百年之计。",
	"#gz_tangzi:die": "偷工减料，要不得啊……",
	"#gzwenji1": "这，可如何是好？",
	"#gzwenji2": "望先生不吝赐教。",
	"#gztunjiang1": "大恩难报，军粮以资。",
	"#gztunjiang2": "虽有不舍，也只能离家远行了。",
	"#gz_liuqi:die": "身侧之人，歹毒更甚于敌！",
	"#mffengshi1": "雪中送炭？倒不如落井下石！",
	"#mffengshi2": "今发兵援羽，敢问是过是功？",
	"#gz_mifangfushiren:die": "虞翻小儿，你安敢辱我！",
	"#gzbiluan1": "审势夺度，以稳求进。",
	"#gzbiluan2": "进退利弊，自当细细思量。",
	"#gzlixia1": "先生大才，岂可居于人下。",
	"#gzlixia2": "先生贤才，老夫着实佩服。",
	"#gz_shixie:die": "天命之时……已到……",
	"#gzbushi1": "争斗，永远没有赢家。",
	"#gzbushi2": "和平，永远没有输家。",
	"#gzmidao1": "恩结天地，法惠八荒。",
	"#gzmidao2": "行五斗米道，可知暖饱。",
	"#gz_zhanglu:die": "唉，义不敌武，道难御兵……",
	"#quanjin1": "今称魏公，则可以藩卫之名，征吴伐蜀也。",
	"#quanjin2": "明公受封，正合天心人意！",
	"#zaoyun1": "开渠输粮，振军之心，破敌之胆！",
	"#zaoyun2": "兵精粮足，胜局已定！",
	"#gz_dongzhao:die": "一生无愧，又何惧身后之议……",
	"#zhuhai_gz_re_xushu1": "今日当要替天行道。",
	"#zhuhai_gz_re_xushu2": "我容得你，天不容你！",
	"#gzjiancai1": "得此贤士，如鱼得水。",
	"#gzjiancai2": "将军，在下可举荐一人。",
	"#gz_re_xushu:die": "未尽孝道，抱憾此生……",
	"#donggui1": "闻伯符立业，今特来相助。",
	"#donggui2": "臣虽驽钝，愿以此腔热血报国。",
	"#fengyang1": "谁也休想染指江东寸土！",
	"#fengyang2": "如此咽喉要地，吾当亲力守之。",
	"#gz_wujing:die": "憾未能见，我江东一统天下之时……",
	"#gzzhidao1": "一朝得势，自当尽诸其力！",
	"#gzzhidao2": "本王要的，没有得不到的！",
	"#gzyjili1": "处处受制于人，难施拳脚。",
	"#gzyjili2": "寄居人下，终是气短。",
	"#gz_yanbaihu:die": "江东，有我一半……",
	"#gzchenglve1": "如此大胜，皆由我一人谋划。",
	"#gzchenglve2": "画谋定计，谁堪与我比较。",
	"#gzshicai1": "阿瞒，苦思之事，我早有良策。",
	"#gzshicai2": "策略已有，按部就班即可得胜。",
	"#gz_xuyou:die": "阿瞒，你竟忘恩负义！！",
	"#gzbaolie1": "废话少说，受死吧，喝！",
	"#gzbaolie2": "当今曹营之将，一个能打的都没有！",
	"#gz_xiahouba:die": "不好，有埋伏！呃！",
	"#gzcongcha1": "窥一斑而知全豹。",
	"#gzcongcha2": "问一事则明其心。",
	"#xinfu_gongqing_gz_panjun1": "水至清则无鱼，人至察则可无过。",
	"#xinfu_gongqing_gz_panjun2": "若人人怀公忘私，则天下早定矣。",
	"#gz_panjun:die": "密谋既泄，难处奸贼啊……",
	"#gzxishe1": "伏箭灭破虏，坚城拒讨逆。",
	"#gzxishe2": "什么江东猛虎？还不是我箭下之鬼！",
	"#gz_huangzu:die": "今日不过是成王败寇，哼！动手吧！",
	"#aocai_gz_zhugeke1": "诸位可知，自古英雄出少年！",
	"#aocai_gz_zhugeke2": "恪乞笔再添二字，还请陛下一观。",
	"#gzduwu1": "此战罪在当代，然功在千秋。",
	"#gzduwu2": "昔秦灭六国之事，足表养敌之患！",
	"#gz_zhugeke:die": "祸及三族，愧对父亲……",
	"#gzlianpian1": "公之大才，当于行伍建功，安能空老林泉？",
	"#gzlianpian2": "你我旧识，此险，望兄搭救之！",
	"#gz_xf_sufei:die": "身陷庸主而不自知，今日终陷囹圄……",
	"#gztongduo1": "统荆益二州诸物之价，以为民生国祚之大计。",
	"#gztongduo2": "铸直百之钱，可平物价，定军民之心。",
	"#qingyin1": "功成身退，再不问世间诸事。",
	"#qingyin2": "天下既定，我亦当遁迹匿踪，颐养天年矣。",
	"#gz_liuba:die": "家国将逢巨变，奈何此身先陨……",
	"#daming1": "孝直溢美之言，特以此小利报之，还望笑纳。",
	"#daming2": "孟起，莫非甘心为他人座下之客。",
	"#xiaoni1": "如此荒辈之徒为主，成何用也。",
	"#xiaoni2": "公既如此，恕在下诚难留之。",
	"#gz_pengyang:die": "人言我心大志寡，难可保安，果然如此，唉……",
	"#gzjuejue1": "舍小家而取大胜，何惜之有？！",
	"#gzjuejue2": "今家小虽陷敌手，安敢以私废公！",
	"#gzfangyuan1": "布阵合围，滴水不漏，待敌自溃。",
	"#gzfangyuan2": "乘敌阵未稳，待我斩将刈旗，先奋士气！",
	"#gz_zhuling:die": "半生曹家麾下将，终是，丞相眼中，倒戈臣……",

	"#gz_yuji:die": "幻化之物，终是算不得真呐……",
	"#duoshi1": "国之大计，审势为先。",
	"#duoshi2": "依今日之大势，当行此计。",
	"#gz_luxun:die": "还以为我已经不再年轻……",
	"#jianchu1": "休想全身而退！",
	"#jianchu2": "杀到你丢盔弃甲！",
	"#gz_mateng:die": "儿子，为爹报仇啊！",
	"#shuangren1": "吃我一记三尖两刃刀！",
	"#qingcheng1": "我和你们真是投缘啊。",
	"#qingcheng2": "哼，眼睛都直了呀。",

	"#baoling1": "待吾大开杀戒，哈哈哈哈！",
	"#baoling2": "大丈夫，岂能妇人之仁？",
	"#zhangwu1": "遁剑归一，有凤来仪。",
	"#zhangwu2": "剑气化龙，听朕雷动！",
	"#jizhao1": "仇未报，汉未兴，朕志犹在！",
	"#jizhao2": "王业不偏安，起师再兴汉！",
	"#rerende_gz_jun_liubei1": "勿以恶小而为之，勿以善小而不为。",
	"#rerende_gz_jun_liubei2": "君才十倍于丕，必能安国成事。",
	"#shouyue": "布德而昭仁，见旗如见朕！",
	"#shouyue_wusheng1": "关将军雄姿，由你再现！",
	"#shouyue_wusheng2": "再次威震华夏，必成汉兴佳话！",
	"#shouyue_paoxiao1": "杀！把他捅成马蜂窝！",
	"#shouyue_paoxiao2": "昔日长坂坡，今日再咆哮！",
	"#shouyue_longdan1": "请收好，此乃子龙枪法。",
	"#shouyue_longdan2": "子龙将助你一臂之力。",
	"#shouyue_tieji1": "西凉的马蹄声，真好听。",
	"#shouyue_tieji2": "马家军风采何在？！",
	"#shouyue_liegong1": "当年老将军冲锋，也是这时机。",
	"#shouyue_liegong2": "百步穿杨，立功拜将！",
	"#gz_jun_liubei:die": "若嗣子可辅，辅之；如其不才，君可自取……",
	"#wuxin1": "冀悟迷惑之心。",
	"#wuxin2": "吾已明此救世之术矣。",
	"#hongfa1": "苍天已死，黄天当立！",
	"#hongfa2": "汝等安心，吾乃大贤良师也。",
	"#hongfa3": "此法可助汝等脱离苦海。",
	"#huangjintianbingfu1": "此乃天将天兵，尔等妖孽看着！",
	"#huangjintianbingfu2": "且作一法，召唤神力！",
	"#huangjintianbingfu3": "吾有天神护体！",
	"#wendao1": "诚心求天地之道，救世之法。",
	"#wendao2": "求太平之法以安天下。",
	"#gz_jun_zhangjiao:die": "天，真要灭我……",
	"#jiahe": "嘉禾生，大吴兴！",
	"#yuanjiangfenghuotu1": "保卫国家，人人有责！",
	"#yuanjiangfenghuotu2": "连绵的烽火，就是对敌人最好的震慑！",
	"#yuanjiangfenghuotu3": "有敌来犯，速速御敌！",
	"#yuanjiangfenghuotu4": "来，扶孤上马迎敌！",
	"#jiahe_reyingzi1": "大吴江山，儒将辈出。",
	"#jiahe_reyingzi2": "千夫奉儒将，百兽伏麒麟。",
	"#jiahe_haoshi1": "朋友有难，当倾囊相助。",
	"#jiahe_haoshi2": "好东西，就要跟朋友分享。",
	"#jiahe_shelie1": "军中多务，亦当涉猎。",
	"#jiahe_shelie2": "少说话，多看书。",
	"#jiahe_duoshi1": "广施方略，以观其变。",
	"#jiahe_duoshi2": "莫慌，观察好局势再做行动。",
	"#lianzi1": "税以足食，赋以足兵。",
	"#lianzi2": "府库充盈，国家方能强盛！",
	"#zhiheng_gz_jun_sunquan1": "二宫并阙，孤之所愿。",
	"#zhiheng_gz_jun_sunquan2": "鲁王才兼文武，堪比太子。",
	"#jubao1": "四海之宝，孤之所爱。",
	"#jubao2": "夷洲，扶南，辽东，皆大吴臣邦也！",
	"#gz_jun_sunquan:die": "朕的江山，要倒下了么……",
	"#yigui1": "百鬼众魅，自缚见形。",
	"#yigui2": "来去无踪，众谓诡异。",
	"#jihun1": "魂聚则生，魂散则弃。",
	"#jihun2": "魂羽化游，以辅四方。",
	"#xuanlve1": "强兵破阵，斩将于须臾。",
	"#xuanlve2": "轻装急袭，破敌于千里。",
	"#yongjin1": "冲啊，扬我东吴之勇！",
	"#yongjin2": "东吴虎威，岂是尔等可犯！",
	"#gzkuangcai1": "耳所瞥闻，不忘于心。",
	"#gzkuangcai2": "吾焉能从屠沽儿耶？",
	"#gzshejian1": "伤人的，可不止刀剑！",
	"#gzshejian2": "死公！云等道？",
	"#gzjianliang1": "岂曰少衣食，与君共袍泽！",
	"#gzjianliang2": "义士同心力，粮秣应期来！",
	"#gzweimeng1": "此礼献于友邦，共赴兴汉大业！",
	"#gzweimeng2": "吴有三江之守，何故委身侍魏？",
	"#gz_dengzhi:die": "伯约啊，我帮不了你了……",
	"#gzduannian1": "断思量，莫思量。",
	"#gzduannian2": "一别两宽，不负相思。",
	"#gzlianyou1": "莲花佑兴，业火可兴。",
	"#gzlianyou2": "昔日莲花开，今日红火燃。",

	"#fz_wusheng": "武节不减，圣德加身。",
	"#fz_new_paoxiao": "刚勇奋战，绝不退缩！",
	"#fz_new_longdan": "盘龙卧旋，攻防无解。",
	"#fz_new_tieji": "战骑铁甲，撼动踏阵。",
	"#fz_liegong": "挽弓箭出，流火漫天。",
	"#fz_xinkuanggu": "猎战沙场，我的乐趣。",
	"#keshou1": "仁以待民，自处不败之势。",
	"#keshou2": "宽济百姓，则得战前养备之机。",
	"#gz_lukang:die": "抗仅以君子之交待叔子，未有半分背国之念啊！",
	"#gzfudi1": "弃暗投明，为明公计！",
	"#gzfudi2": "绣虽有降心，奈何贵营难容。",
	"#jianan": "设使天下无孤，不知几人称帝，几人称王？",
	"#wuziliangjiangdao1": "行为军锋，还为后拒！",
	"#wuziliangjiangdao2": "国之良将，五子为先。",
	"#jianan_tuxi1": "以百破万，让孤再看一次！",
	"#jianan_tuxi2": "望将军身影，可去孤之头风病。",
	"#jianan_qiaobian1": "孤之兵道，此一时，彼一时。",
	"#jianan_qiaobian2": "时变，势变，孤唯才是举。",
	"#jianan_xiaoguo1": "使孤梦回辽东者，卿之雄风也！",
	"#jianan_xiaoguo2": "得贤人共治天下，得将军共定天下！",
	"#jianan_jieyue1": "孤之股肱，谁敢不从？嗯？",
	"#jianan_jieyue2": "泰山之高，群山不可及；文则之重，泰山不可及。",
	"#jianan_duanliang1": "孤以为断粮如断肠，卿意下如何？",
	"#jianan_duanliang2": "卿名为“亚夫”，实为“冠军”也！",
	"#huibian1": "吾任天下之智力，以道御之，无所不可。",
	"#huibian2": "青青子衿，悠悠我心。但为君故，沉吟至今。",
	"#gzzongyu1": "驾六龙，乘风而行。行四海，路下之八邦。",
	"#gzzongyu2": "齐桓之功，为霸之首。九合诸侯，一匡天下！", //配音错误？，应为：齐桓之功，为霸之道
	"#gz_jun_caocao:die": "神龟虽寿，犹有竟时。腾蛇乘雾，终为土灰……",
	"#sanchen1": "陈书弼国，当一而再、再而三。",
	"#mingzhe2": "塞翁失马，焉知非福？",
	"#twzhenxi2": "震疆扫寇，袭贼平戎！",
	"#mobiledanshou1": "此诚危难，我定当竭尽全力！",
	"#weishu2": "吴人来犯，当用心戒备。",
	"#gz_yundao1":"春芽不砺冬寒，其必难引暖风归还。",
"#gz_yundao2":"与卿为好之心，似冬风抚面而不寒。",
"#gz_yundao3":"此心哀，如涸泽之鲋，无沫相融。",
"#gz_yundao4":"此心痛，如刀俎犁腹，欲哭无声。",
"#gz_youming1":"我所蹈之节，可以此生践之。",
"#gz_youming2":"衷其情而恪其节，此荀门之教也。",
"#gz_zuilun1":"瞻世受国恩，却未能以才弼国，是罪也。",
"#gz_zuilun2":"美声溢誉，而力不能及，瞻有罪于国。",
"#gz_zuilun3":"宦官弄权掌君，实乃臣下之过也。",
"#gz_zuilun4":"犹豫不决，以致丧师辱国，其罪无可赦也。",
"#gz_zuilun5":"瞻内不能摒除奸宦，外不能守土御敌，愧对陛下。",
"#gz_zuilun6":"绵竹之地今于我，恰如武帝悔轮台。",
"#gz_dishang1":"此番须拼死一战，以赎戴罪之身。",
"#gz_dishang2":"攻须凭计，守则尽胆。",
"#gz_dishang3":"疑兵之法，可保此地无虞。",
"#gz_dishang4":"定使魏军虚实难辨，真假不分！",
"#gz_yisang1":"今日躬桑于西郊，请为大王衣。",
"#gz_yisang2":"清风胧月香怡，请君暂驻小憩。",
"#gz_jiubo1":"陛下任人不明，所托绝非良人。",
"#gz_jiubo2":"吾与太傅同气连枝，一损则俱损。",

"#gz_yunxing1":"老夫古稀之年，恐寿数将尽，不复相见矣。",
"#gz_yunxing2":"今老而难死，唯抽白发作毫锋，挑灯写降笺。",
"#gz_yunxing3":"天象有数，今至于此，非陛下、群臣之过。",
"#gz_yuandao1":"高祖斩蛇而定北极，星河斗转，其位移也。",
"#gz_yuandao2":"周慕孔子遗风，可与刘、扬同轨。",
"#gz_yuandao3":"诸葛公天纵之才而堪堪弼国，况我等凡夫乎？",
"#gz_baoguo1":"自古以来，无寄他国而为天子者也。",
"#gz_baoguo2":"周知天命之年，今冒天下不韪而劝降。",
"#gz_baoguo3":"陛下降，若魏不裂土以封，臣必以古义争之。",
"#gz_zeyu1":"熟读情势，憾无沙场纵横。",
"#gz_zeyu2":"泛舟沧海，风动云帆，送我步青云。",
"#gz_bihun1":"赤心如丹，思虑王室之险。",
"#gz_bihun2":"气节如玉，心忧国家之难。",
"#gz_yinbing1":"情势危急，故为此举以脱一时之困。",
"#gz_yinbing2":"若当下之围不解，何以图千秋之惠？",
"#gz_juanzhi1":"此剑光芒艳发，非凡物也，当以华阴赤土拭之。",
"#gz_juanzhi2":"斗牛间常有紫气，其兆如何，还请阁下解之。",
"#gz_jiaping1":"志蕴数载，今朝逐鹿！",
"#gz_jiaping2":"指点江山五十载，一朝化龙跃金銮！",
"#gz_guikuang1":"横眉养红莲，此花开时，诸侯尽膝行！",
"#gz_guikuang2":"袖中藏莫邪，志高位卑，犹思屠犬豕。",
"#gz_shujuan1":"谋大事者，必察常人所不察。",
"#gz_shujuan2":"蛰伏多载，今朝雄志可展！",
"#gz_jiyuan1":"男胤有德色，愿陛下以备六宫。",
"#gz_jiyuan2":"广集良家，召充选者使吾拣择。",

"#gz_lingzhi1":"须知少时凌云志，曾许人间第一流。",
"#gz_lingzhi2":"欲乘青云扶摇上，少年壮志镇九州！",
"#gz_ruluo1":"初入门庭负豪志，亦得云锦天章去！",
"#gz_ruluo2":"早闻天下智者盛，今朝入京识时贤！",
"#gz_linzhe1":"此位当属汝南袁氏遗才！",
"#gz_linzhe2":"宇内既统，当招揽天下英才！",
"#gz_yamai1":"汝既不才，何以忝居高位？",
"#gz_yamai2":"冀州三十士，当耀于朝。",
"#gz_luanchang1":"欲扫清寰宇，重振朝纲，必诛奸臣！",
"#gz_luanchang2":"杀了你们，天下都是我说的算！",
"#gz_zhulan1":"整顿天下，为国除害！",
"#gz_zhulan2":"陛下在哪，陛下在哪？",
"#gz_gongzhi1":"身负托孤之重，但坐论清谈，此亦可乎？",
"#gz_gongzhi2":"陛下用人之际，臣岂敢身退庙堂！",
"#gz_sheju1":"臣怀二心，不可事君也。",
"#gz_sheju2":"今观汝之行事，老夫亦肝心俱裂。",
"#gz_neiji1":"你我势不两立，必要争个高下，来吧！",
"#gz_neiji2":"必要争个你死我活，方为痛快！",
"#gz_liefa1":"此击必断敌归路！",
"#gz_liefa2":"焚掠浚遒，敌必乱而自伐！",
"#gz_xiejian1":"图财还是保命？亦或者，玉石俱焚？",
"#gz_xiejian2":"朝中亲党下场，汝等的好日子到了！",
"#gz_yinsha1":"今且缓其事，贾后必害太子，然后废后，为太子报仇，亦足以立功，岂徒免祸而已。",
"#gz_yinsha2":"臣且听闻朝野欲废后，而得以复拥太子，甚为狂肆！",
"#gz_guishang1":"这是赏给你的！",
"#gz_guishang2":"别争斗，见者有份！",
"#gz_niubi1":"吾权倾朝野，终有一日夺得这天下！",
"#gz_niubi2":"汝等屡番劝谏与吾志相悖，吾唯从吾心！",
"#gz_ruxin1":"我有红袖挽长缨，可缚诸葛作乘龙。",
"#gz_ruxin2":"身负彩鳞妆彩翼，心有玲珑点灵犀。",
"#gz_linglong1":"木羽裁云织晓雾，栖在梧桐最高处。",
"#gz_linglong2":"穿林铁翅寒，待借东风力，九霄揽月还。",
"#gz_feng_huangyueying:die":"铁翎犹记云深处，曾载春山几万重。",
"#gz_lujii:die":"华亭鹤唳，可复闻乎？",
"#gz_sunxiuu:die":"许我虚名，归我老去，成败转头即飞白。",
"#gz_simalun:die":"大事当以急行，而不可缓图。",
"#gz_yangjun:die":"唉，终是难逃灭门之祸。",
"#gz_simaliang:die":"生此篡逆之世，罪臣难辞其咎。",
"#gz_huoyi:die":"南中初定，蛮河已靖；风雨未晏，归顺新朝。百姓得安，吾无憾矣。",
"#gz_shantao:die":"臣垂没之人，岂可污朝堂乎？",


"#gz_juansui1":"莫说七步，便是七百步、七万步，妾也煮不出豆羹。",
"#gz_juansui2":"众妹妹的枕边风，可比祛火汤更合圣意？",
"#gz_pizou1":"青砖浸透红颜泪，朱墙难困腊梅香。",
"#gz_pizou2":"素衣何惧霜雪重？俯仰无愧，不须低眉！",
"#gz_renwan:die":"深情自古总被负，魏宫尽是薄情人。",

"#gz_fuhui1":"画入我眸寻兰黛，千度回首，唯有香如故。",
"#gz_fuhui2":"我入画中访青笺，一笔流年，繁花犹香艳。",
"#gz_mohua1":"画中月照百世人，画外人识百花香。",
"#gz_mohua2":"三分墨染七分意，层峦似有清泉来。",
"#gz_xuwen:die":"丹青从不败，白头总佳人。",

"#gz_qiaoshi1":"采樵南山下，拾君一片心。",
"#gz_qiaoshi2":"山有木兮木成樵，心悦君兮君可知。",
"#gz_yanyu1":"夏燕不羡黄金屋，只栖君家檐下巢。",
"#gz_yanyu2":"红袖不解相思意，凭燕传语慰君心。",
"#gz_xiahoushi:die":"可怜城头白发妪，至死不见征夫还。",

"#gz_zhenlie1":"素颜风吹胭脂折，巾帼红妆贞烈战！",
"#gz_zhenlie2":"贞洁烈志，与城共守。",
"#gz_miji1":"共勉卒勋，不可顺逆转之意。",
"#gz_miji2":"管仲入齐，立九合之功。",
"#gz_wangyi:die":"家国俱毁，我已无容身之所。",

"#gz_zicai1":"我意已决，诸兄何复多言？",
"#gz_zicai2":"此去如若不成，吾宁殉志而终。",
"#gz_zhengmu1":"今幸明主亲召，良安可不应乎？",
"#gz_zhengmu2":"皇叔辅者少有，良当及时应召。",
"#gz_feng_maliang:die":"此生行忠守义，已无愧我心。",

"#gz_anxu1":"人不患寡而患不均，均之可恤人心。",
"#gz_anxu2":"闻他山之花馥郁，欲借之以献佛。",
"#gz_zhuiyi1":"青雀还巢日，望君勿忘我。",
"#gz_zhuiyi2":"昔年与君好，经年亦如是。",
"#gz_bulianshi:die":"花消叶落春不在，岁月如何败佳人？",

"#gz_junwei1":"这一身装备，叫你们开开眼界！",
"#gz_junwei2":"和我来一场华丽的战斗吧！",
"#gz_junwei3":"看看你的身后吧，蠢货！",
"#gz_junwei4":"拔剑断水，起波澜而涤大吴之江。",
"#gz_heqi:die":"你的刀，比我还快……",

"#gz_niejiang1":"周武继文王之志而开国百年，今吾亦可为之。",
"#gz_niejiang2":"父起于微末而定海内，今承王爵，当以死效之。",
"#gz_kuizhen1":"贼尚惧孔明一州之地，今敢来攻我邪！",
"#gz_kuizhen2":"尔等忘北地之风乎？尔等忘北地之寒乎？",
"#gz_gongsunxiu:die":"司马懿老谋深算，非常人可敌。",

"#gz_hexi1":"哼，不过一南来貉子罢了！",
"#gz_hexi2":"名门之仪，岂容尔等蛮夫沾染！",
"#gz_hexi1":"一言为界，你我殊途。",
"#gz_hejue1":"经此一事，方知情重。",
"#gz_hejue2":"夫君，昔日之言，休要再提。",
"#gz_hejue3":"破镜重圆，完璧合一。",
"#gz_kuaishi:die":" 玉已碎，人已亡……勿复相思……",
};
