-- The upstream hegemony package now bundles an older Fengsui package. Load
-- the official packages explicitly so the standalone current Fengsui package
-- is the only one registering Fengsui generals and cards.
local hegemonyPackages = require "packages/fengsui/pkg/hegemony_packages"

Fk:loadTranslationTable{
  ["fengsui"] = "烽燧燎原",
  ["fengsui_hebi"] = "烽燧燎原-合璧",
  ["fengsui_liwu"] = "烽燧燎原-离骛",
  ["fengsui_shiyi"] = "烽燧燎原-拾遗",
  ["fengsui_cards"] = "<font color='red'>烽燧燎原卡牌</font>",
  ["fengsui_mode"] = "<font color='green'>燎原之战</font>",
  ["fengsui_effect"] = "烽燧燎原-特效",
}

require "packages/fengsui/pkg/compat"

local fengsui_hebi = require "packages/fengsui/pkg/fengsui_hebi"
local fengsui_cards = require "packages/fengsui/pkg/fengsui_cards"
local fengsui_liwu = require "packages/fengsui/pkg/fengsui_liwu"
local fengsui_shiyi = require "packages/fengsui/pkg/fengsui_shiyi"
local fengsui_effect = require "packages/fengsui/pkg/fengsui_effect"
local fengsui_mode = require "packages/fengsui/pkg/fengsui_mode"

require("packages/fengsui/pkg/audio_overlay")(hegemonyPackages, fengsui_cards)
require "packages/fengsui/pkg/runtime_translations"

-- Voice overrides are loaded last so official packages cannot replace them.
Fk:loadTranslationTable{
  ["fengsui_hebi"] = "烽燧燎原-合璧",
  ["fengsui_hebi_choice"] = "合璧",
  ["$heg__chengguan1"] = "摧城不必急火，溃堤只需蚁穴。",
  ["$heg__chengguan2"] = "这点本事，也敢来挡我的路。",
  ["$heg__chengguan_heg__simaying1"] = "摧城不必急火，溃堤只需蚁穴。",
  ["$heg__chengguan_heg__simaying2"] = "这点本事，也敢来挡我的路。",
  ["$heg__chuchong1"] = "杀一蠹而安宗室，此等功业，谁敢与本王争？",
  ["$heg__chuchong2"] = "同宗若敢挡路，也不过是另一条虫！",
  ["$heg__chuchong3"] = "孙秀妖佞已诛，赵王逆党一个也休想逃！",
  ["$heg__chuchong4"] = "本王奉诏举义，诛的正是朝廷蠹虫！",
  ["$heg__chuchong_heg__simajiong1"] = "杀一蠹而安宗室，此等功业，谁敢与本王争？",
  ["$heg__chuchong_heg__simajiong2"] = "同宗若敢挡路，也不过是另一条虫！",
  ["$heg__chuchong_heg__simajiong3"] = "孙秀妖佞已诛，赵王逆党一个也休想逃！",
  ["$heg__chuchong_heg__simajiong4"] = "本王奉诏举义，诛的正是朝廷蠹虫！",
  ["$heg__dufu1"] = "满朝皆是庸碌之辈，本王一人足以镇天下！",
  ["$heg__dufu2"] = "洛阳诸事，无须天子点头，本王说了便算！",
  ["$heg__dufu3"] = "众叛亲离又如何？这朝纲仍握在本王手中！",
  ["$heg__dufu4"] = "谁道独夫必败？本王偏要独掌山河！",
  ["$heg__dufu_heg__simajiong1"] = "满朝皆是庸碌之辈，本王一人足以镇天下！",
  ["$heg__dufu_heg__simajiong2"] = "洛阳诸事，无须天子点头，本王说了便算！",
  ["$heg__dufu_heg__simajiong3"] = "众叛亲离又如何？这朝纲仍握在本王手中！",
  ["$heg__dufu_heg__simajiong4"] = "谁道独夫必败？本王偏要独掌山河！",
  ["$heg__fengguo1"] = "速整兵马，我等宗亲共赴国难！",
  ["$heg__fengguo2"] = "奸凶谋夺皇位，我为社稷除害！",
  ["$heg__fengguo_heg__simayij1"] = "速整兵马，我等宗亲共赴国难！",
  ["$heg__fengguo_heg__simayij2"] = "奸凶谋夺皇位，我为社稷除害！",
  ["$heg__gouni1"] = "天子圣驾在此，诸公何不随行？",
  ["$heg__gouni2"] = "本王势尽，然同宗之志未绝。",
  ["$heg__gouni_heg__simayong1"] = "天子圣驾在此，诸公何不随行？",
  ["$heg__gouni_heg__simayong2"] = "本王势尽，然同宗之志未绝。",
  ["$heg__guorui1"] = "我等奉诏入京，为朝扫除奸邪。",
  ["$heg__guorui2"] = "与亮图谋者，皆连坐！",
  ["$heg__guorui_heg__simawei1"] = "我等奉诏入京，为朝扫除奸邪。",
  ["$heg__guorui_heg__simawei2"] = "与亮图谋者，皆连坐！",
  ["$heg__huluan1"] = "骨肉相残，同室操戈，但为天下除此蠢耳。",
  ["$heg__huluan2"] = "疑我、惧我、叛我者，共沉沦吧！",
  ["$heg__huluan_heg__simayue1"] = "骨肉相残，同室操戈，但为天下除此蠢耳。",
  ["$heg__huluan_heg__simayue2"] = "疑我、惧我、叛我者，共沉沦吧！",
  ["$heg__mieyi1"] = "暂敛锋芒，待时而动。",
  ["$heg__mieyi2"] = "不识天命者，不得天葬！",
  ["$heg__mieyi_heg__simayong1"] = "暂敛锋芒，待时而动。",
  ["$heg__mieyi_heg__simayong2"] = "不识天命者，不得天葬！",
  ["$heg__neiji1"] = "顾命之权，岂可旁落汝南！",
  ["$heg__neiji2"] = "贾氏难制，当以亲党宿卫宫禁。",
  ["$heg__neiji_heg__yangjun1"] = "顾命之权，岂可旁落汝南！",
  ["$heg__neiji_heg__yangjun2"] = "贾氏难制，当以亲党宿卫宫禁。",
  ["$heg__xiejian1"] = "朝中亲党下场，汝等的好日子到了！",
  ["$heg__xiejian2"] = "图财还是保命？亦或者，玉石俱焚？",
  ["$heg__xiejian_heg__sunxiuj1"] = "朝中亲党下场，汝等的好日子到了！",
  ["$heg__xiejian_heg__sunxiuj2"] = "图财还是保命？亦或者，玉石俱焚？",
  ["$heg__yinfu1"] = "滔天之势，与日俱盛。",
  ["$heg__yinfu2"] = "权柄之下，何来异声？",
  ["$heg__yinfu_heg__simayue1"] = "滔天之势，与日俱盛。",
  ["$heg__yinfu_heg__simayue2"] = "权柄之下，何来异声？",
  ["$heg__yinsha1"] = "臣且听闻朝野欲废后，而得以复拥太子，甚为狂肆！",
  ["$heg__yinsha2"] = "今且缓其事，贾后必害太子，然后废后，为太子报仇，亦足以立功，岂徒免祸而已。",
  ["$heg__yinsha_heg__sunxiuj1"] = "臣且听闻朝野欲废后，而得以复拥太子，甚为狂肆！",
  ["$heg__yinsha_heg__sunxiuj2"] = "今且缓其事，贾后必害太子，然后废后，为太子报仇，亦足以立功，岂徒免祸而已。",
  ["~heg__simajiong"] = "司马乂小儿……本王竟败在你手！",
  ["~heg__simawei"] = "我今就死，天下将乱，谁能苟全？",
  ["~heg__simayij"] = "金墉城冷，人心更寒。",
  ["~heg__simaying"] = "我死之后，天下安乎不安乎？",
  ["~heg__simayong"] = "保守孤城，仍不足焉？",
  ["~heg__simayue"] = "天不佑晋，岂我一人之过。",
  ["~heg__sunxiuj"] = "许我虚名，归我老去，成败转头即非白，哈哈哈......",
  ["~heg__yangjun"] = "宫门生变，杨氏休矣，唉......",
  ["$heg__liaoye1"] = "这晋室江山，本宫要它烧成何样，它便是何样！",
  ["$heg__liaoye2"] = "尔等尽管选边，留下的那一边，本宫亲自烧个干净。",
  ["$heg__liaoye3"] = "区区朝臣，也敢妄议本宫的手段？",
  ["$heg__liaoye4"] = "烈火焚城，正好替本宫筛尽忤逆之徒。",
  ["$heg__liaoye_heg__jiananfeng1"] = "这晋室江山，本宫要它烧成何样，它便是何样！",
  ["$heg__liaoye_heg__jiananfeng2"] = "尔等尽管选边，留下的那一边，本宫亲自烧个干净。",
  ["$heg__liaoye_heg__jiananfeng3"] = "区区朝臣，也敢妄议本宫的手段？",
  ["$heg__liaoye_heg__jiananfeng4"] = "烈火焚城，正好替本宫筛尽忤逆之徒。",
  ["$heg__fangzi1"] = "废谁立谁，不过本宫一句话罢了。",
  ["$heg__fangzi2"] = "位置坐得久了，便真当自己配得上？",
  ["$heg__fangzi3"] = "今日借你一席之地，明日便可收你一条命。",
  ["$heg__fangzi4"] = "朝堂如棋，诸位都是本宫手中的子。",
  ["$heg__fangzi_heg__jiananfeng1"] = "废谁立谁，不过本宫一句话罢了。",
  ["$heg__fangzi_heg__jiananfeng2"] = "位置坐得久了，便真当自己配得上？",
  ["$heg__fangzi_heg__jiananfeng3"] = "今日借你一席之地，明日便可收你一条命。",
  ["$heg__fangzi_heg__jiananfeng4"] = "朝堂如棋，诸位都是本宫手中的子。",
  ["$heg__liudu1"] = "本宫纵入黄泉，也要看司马氏骨肉相食！",
  ["$heg__liudu2"] = "毒已入骨，尔等谁也休想独善其身！",
  ["$heg__liudu3"] = "杀了本宫又如何？这天下早已烂透了！",
  ["$heg__liudu4"] = "来啊，且看这满朝冠冕还能撑到几时！",
  ["$heg__liudu_heg__jiananfeng1"] = "本宫纵入黄泉，也要看司马氏骨肉相食！",
  ["$heg__liudu_heg__jiananfeng2"] = "毒已入骨，尔等谁也休想独善其身！",
  ["$heg__liudu_heg__jiananfeng3"] = "杀了本宫又如何？这天下早已烂透了！",
  ["$heg__liudu_heg__jiananfeng4"] = "来啊，且看这满朝冠冕还能撑到几时！",
  ["~heg__jiananfeng"] = "贾氏竟败于尔等鼠辈……本宫不服！",
  ["$heg__fuzheng1"] = "承景王之嗣，当佐宗室以安社稷。",
  ["$heg__fuzheng2"] = "宗亲有难，攸岂可袖手旁观。",
  ["$heg__fuzheng3"] = "辅弼朝纲，所念唯国，不计私门。",
  ["$heg__fuzheng4"] = "愿移此位，换宗室一脉得安。",
  ["$heg__yunde1"] = "德不独善，当分惠于宗亲。",
  ["$heg__yunde2"] = "知人而后任之，量才而后授之。",
  ["$heg__yunde3"] = "兄弟同心，何必以储位相疑。",
  ["$heg__yunde4"] = "进不争权，退不避责，此为臣节。",
  ["~SP_heg__simayou"] = "臣弟别无他志，陛下何以疑我至此……",
  ["$heg__xiace_fengsui_heg__lujii1"] = "观古今于须臾，察得失于方寸。",
  ["$heg__xiace_fengsui_heg__lujii2"] = "审势而后落子，制敌只在一念。",
  ["$ld__qice_fengsui_heg__lujii1"] = "笼天地于形内，挫万物于笔端。",
  ["$ld__qice_fengsui_heg__lujii2"] = "入洛非为虚名，当以奇谋匡济时艰。",
  ["~fengsui_heg__lujii"] = "华亭鹤唳，可复闻乎？",
  ["$heg__bingxin_fengsui_heg__huoyi1"] = "南疆霜众，报国丹心未曾冷却；",
  ["$heg__bingxin_fengsui_heg__huoyi2"] = "心如寒玉，纵易旌旗，不易臣节。",
  ["$niaoxiang_fengsui_heg__huoyi1"] = "诸军分翼而进，合围勿纵！",
  ["$niaoxiang_fengsui_heg__huoyi2"] = "断其归路，一击定南疆！",
}

return {
  fengsui_hebi,
  fengsui_cards,
  fengsui_liwu,
  fengsui_shiyi,
  fengsui_effect,
  fengsui_mode,
}
