'use strict';
decadeModule.import(function(lib, game, ui, get, ai, _status){
	decadeUI.dynamicSkin = {
		caomao: {
			经典形象: {
				name: "曹髦/经典形象/XingXiang",
				scale: 0.35,
				x: [0,0.5],
				y: [0,0.5],
				beijing: {
					name: "曹髦/经典形象/BeiJing",
					scale: 0.35,
					x: [0,0.98],
					y: [0,0.47],
				},
			},
		},
		liuyan: {
			龙兴蜀川: {
				name: "刘焉/龙兴蜀川/XingXiang",
				scale: 0.35,
				x: [0,0.5],
				y: [0,0.5],
				beijing: {
					name: "刘焉/龙兴蜀川/BeiJing",
					scale: 0.35,
					x: [0,0.98],
					y: [0,0.47],
				},
			},
		},
		quyi: {
			扬威立刀: {
				name: "麴义/扬威立刀/XingXiang",
				scale: 0.35,
				x: [0,0.5],
				y: [0,0.5],
				beijing: {
					name: "麴义/扬威立刀/BeiJing",
					scale: 0.35,
					x: [0,0.98],
					y: [0,0.47],
				},
			},
			磐河对峙: {
				name: "麴义/磐河对峙/daiji2",
				scale: 0.35,
				x: [0,0.5],
				y: [0,0.5],
				shizhounian: true,
				background: "麴义/磐河对峙/static_bg.png",
				beijing: {
					name: "麴义/磐河对峙/beijing",
					scale: 0.35,
					x: [0,0.98],
					y: [0,0.47],
				},
				chuchang: {
					name: "麴义/磐河对峙/chuchang",
					scale: 0.7,
				},
			},
			竞驹伏骊: {
				name: "麴义/竞驹伏骊/xingxiang",
				scale: 0.35,
				version: "4.0",
				json: true,
				x: [0,0.5],
				y: [0,0.5],
				beijing: {
					name: "麴义/竞驹伏骊/beijing",
					scale: 0.35,
					version: "4.0",
					json: true,
					x: [0,0.98],
					y: [0,0.47],
				},
			},
			虎贲冠勇: {
				name: "麴义/虎贲冠勇/daiji2",
				scale: 0.35,
				x: [0,0.5],
				y: [0,0.5],
				shizhounian: true,
				beijing: {
					name: "麴义/虎贲冠勇/beijing",
					scale: 0.35,
					x: [0,0.98],
					y: [0,0.47],
				},
				chuchang: {
					name: "麴义/虎贲冠勇/chuchang",
					scale: 0.7,
				},
				gongji: {
					name: "麴义/虎贲冠勇/chuchang2",
					scale: 0.35,
				},
				teshu: {
					name: "麴义/虎贲冠勇/chuchang2",
					scale: 0.35,
				},
				zhishixian: {
					name: "麴义/虎贲冠勇/shouji2",
					scale: 0.7,
					delay: 0.3,
					speed: 0.8,
					effect: {
						name: "麴义/虎贲冠勇/shouji",
						scale: 0.7,
						delay: 0.3,
						speed: 0.8,
					},
				},
			},
		},
		shen_simayi: {
			鉴往知来: {
				name: "神司马懿/鉴往知来/XingXiang",
				scale: 0.35,
				x: [0,0.5],
				y: [0,0.5],
				beijing: {
					name: "神司马懿/鉴往知来/BeiJing",
					scale: 0.35,
					x: [0,0.98],
					y: [0,0.47],
				},
			},
		},
		guansuo: {
			万花簇威: {
				name: "关索/万花簇威/daiji2",
				scale: 0.35,
				x: [0,0.5],
				y: [0,0.5],
				shizhounian: true,
				background: "关索/万花簇威/static_bg.png",
				beijing: {
					name: "关索/万花簇威/beijing",
					scale: 0.35,
					x: [0,0.98],
					y: [0,0.47],
				},
				chuchang: {
					name: "关索/万花簇威/chuchang",
					scale: 0.7,
				},
			},
			依心缱绻: {
				name: "关索/依心缱绻/XingXiang",
				scale: 0.35,
				x: [0,0.5],
				y: [0,0.5],
				beijing: {
					name: "关索/依心缱绻/BeiJing",
					scale: 0.35,
					x: [0,0.98],
					y: [0,0.47],
				},
			},
			兔娇春浓: {
				name: "关索/兔娇春浓/daiji2",
				scale: 0.35,
				x: [0,0.5],
				y: [0,0.5],
				shizhounian: true,
				beijing: {
					name: "关索/兔娇春浓/beijing",
					scale: 0.35,
					x: [0,0.98],
					y: [0,0.47],
				},
				chuchang: {
					name: "关索/兔娇春浓/chuchang",
					scale: 0.7,
				},
				gongji: {
					name: "关索/兔娇春浓/chuchang2",
					scale: 0.35,
				},
				teshu: {
					name: "关索/兔娇春浓/chuchang2",
					scale: 0.35,
				},
				zhishixian: {
					name: "关索/兔娇春浓/shouji2",
					scale: 0.7,
					delay: 0.3,
					speed: 0.8,
					effect: {
						name: "关索/兔娇春浓/shouji",
						scale: 0.7,
						delay: 0.3,
						speed: 0.8,
					},
				},
			},
			天赐良缘: {
				name: "关索/天赐良缘/daiji",
				scale: 0.35,
				version: "4.0",
				x: [0,0.5],
				y: [0,0.5],
				shizhounian: true,
				background: "关索/天赐良缘/static_bg.png",
				chuchang: {
					name: "关索/天赐良缘/chuchang",
					scale: 0.7,
					version: "4.0",
				},
			},
			承父武志: {
				name: "关索/承父武志/xingxiang",
				scale: 0.35,
				version: "4.0",
				x: [0,0.5],
				y: [0,0.5],
				beijing: {
					name: "关索/承父武志/beijing",
					scale: 0.35,
					version: "4.0",
					x: [0,0.98],
					y: [0,0.47],
				},
			},
			虎年七夕: {
				name: "关索/虎年七夕/XingXiang",
				scale: 0.35,
				x: [0,0.5],
				y: [0,0.5],
				beijing: {
					name: "关索/虎年七夕/BeiJing",
					scale: 0.35,
					x: [0,0.98],
					y: [0,0.47],
				},
			},
			鼠年中秋: {
				name: "关索/鼠年中秋/XingXiang",
				scale: 0.35,
				x: [0,0.5],
				y: [0,0.5],
				beijing: {
					name: "关索/鼠年中秋/BeiJing",
					scale: 0.35,
					x: [0,0.98],
					y: [0,0.47],
				},
			},
		},
		re_jushou: {
			策胜珠玑: {
				name: "界沮授/策胜珠玑/xingxiang",
				scale: 0.35,
				version: "4.0",
				json: true,
				x: [0,0.5],
				y: [0,0.5],
				beijing: {
					name: "界沮授/策胜珠玑/beijing",
					scale: 0.35,
					version: "4.0",
					json: true,
					x: [0,0.98],
					y: [0,0.47],
				},
			},
		},
		shen_sunquan: {
			冠绝天下: {
				name: "神孙权/冠绝天下/daiji",
				scale: 0.35,
				version: "4.0",
				x: [0,0.5],
				y: [0,0.5],
				shizhounian: true,
				background: "神孙权/冠绝天下/static_bg.png",
				chuchang: {
					name: "神孙权/冠绝天下/chuchang",
					scale: 0.7,
					version: "4.0",
				},
			},
		},
		shen_machao: {
			迅骛惊雷: {
				name: "神马超/迅骛惊雷/daiji2",
				scale: 0.35,
				x: [0,0.5],
				y: [0,0.5],
				shizhounian: true,
				background: "神马超/迅骛惊雷/static_bg.png",
				beijing: {
					name: "神马超/迅骛惊雷/beijing",
					scale: 0.35,
					x: [0,0.98],
					y: [0,0.47],
				},
				chuchang: {
					name: "神马超/迅骛惊雷/chuchang",
					scale: 0.7,
				},
				gongji: {
					name: "神马超/迅骛惊雷/chuchang2",
					scale: 0.35,
				},
				teshu: {
					name: "神马超/迅骛惊雷/chuchang2",
					scale: 0.35,
				},
				zhishixian: {
					name: "神马超/迅骛惊雷/shouji2",
					scale: 0.7,
					delay: 0.3,
					speed: 0.8,
					effect: {
						name: "神马超/迅骛惊雷/shouji",
						scale: 0.7,
						delay: 0.3,
						speed: 0.8,
					},
				},
			},
			雷挝缚苍: {
				name: "神马超/雷挝缚苍/daiji2",
				scale: 0.35,
				x: [0,0.5],
				y: [0,0.5],
				shizhounian: true,
				background: "神马超/雷挝缚苍/static_bg.png",
				beijing: {
					name: "神马超/雷挝缚苍/beijing",
					scale: 0.35,
					x: [0,0.98],
					y: [0,0.47],
				},
				chuchang: {
					name: "神马超/雷挝缚苍/chuchang",
					scale: 0.7,
				},
			},
		},
		xushao: {
			欢-评世雕龙: {
				name: "许劭/欢-评世雕龙/daiji",
				scale: 0.35,
				version: "4.0",
				x: [0,0.5],
				y: [0,0.5],
				shizhounian: true,
				background: "许劭/欢-评世雕龙/static_bg.png",
				chuchang: {
					name: "许劭/欢-评世雕龙/chuchang",
					scale: 0.7,
					version: "4.0",
				},
			},
		},
		guanyu: {
			武动乾坤: {
				name: "关羽/武动乾坤/daiji",
				scale: 0.35,
				version: "4.0",
				x: [0,0.5],
				y: [0,0.5],
				shizhounian: true,
				background: "关羽/武动乾坤/static_bg.png",
				chuchang: {
					name: "关羽/武动乾坤/chuchang",
					scale: 0.7,
					version: "4.0",
				},
			},
		},
		zhangxuan: {
			静谧怜蝶: {
				name: "张嫙/静谧怜蝶/daiji",
				scale: 0.35,
				version: "4.0",
				x: [0,0.5],
				y: [0,0.5],
				shizhounian: true,
				background: "张嫙/静谧怜蝶/static_bg.png",
				chuchang: {
					name: "张嫙/静谧怜蝶/chuchang",
					scale: 0.7,
					version: "4.0",
				},
			},
		},
		bailingyun: {
			蝶翼婉渡: {
				name: "柏灵筠/蝶翼婉渡/daiji2",
				scale: 0.35,
				x: [0,0.5],
				y: [0,0.5],
				shizhounian: true,
				background: "柏灵筠/蝶翼婉渡/static_bg.png",
				beijing: {
					name: "柏灵筠/蝶翼婉渡/beijing",
					scale: 0.35,
					x: [0,0.98],
					y: [0,0.47],
				},
				chuchang: {
					name: "柏灵筠/蝶翼婉渡/chuchang",
					scale: 0.7,
				},
			},
		},
		shen_dengai: {
			经典形象: {
				name: "神邓艾/经典形象/daiji",
				scale: 0.35,
				version: "4.0",
				x: [0,0.5],
				y: [0,0.5],
				background: "神邓艾/经典形象/static_bg.png",
			},
		},
		shen_diaochan: {
			瑶光闭月: {
				name: "神貂蝉/瑶光闭月/daiji",
				scale: 0.35,
				version: "4.0",
				x: [0,0.5],
				y: [0,0.5],
				shizhounian: true,
				background: "神貂蝉/瑶光闭月/static_bg.png",
				chuchang: {
					name: "神貂蝉/瑶光闭月/chuchang",
					scale: 0.7,
					version: "4.0",
				},
			},
		},
		baosanniang: {
			天赐良缘: {
				name: "鲍三娘/天赐良缘/daiji",
				scale: 0.35,
				version: "4.0",
				x: [0,0.5],
				y: [0,0.5],
				shizhounian: true,
				background: "鲍三娘/天赐良缘/static_bg.png",
				chuchang: {
					name: "鲍三娘/天赐良缘/chuchang",
					scale: 0.7,
					version: "4.0",
				},
			},
		},
		dc_sunhanhua: {
			蛇年春节: {
				name: "孙寒华/蛇年春节/XingXiang",
				scale: 0.35,
				x: [0,0.5],
				y: [0,0.5],
				beijing: {
					name: "孙寒华/蛇年春节/BeiJing",
					scale: 0.35,
					x: [0,0.98],
					y: [0,0.47],
				},
			},
		},
		wu_luxun: {
			经典形象: {
				x: [0,0.5],
				y: [0,0.5],
				name: "武陆逊/经典形象/wumiao_luxun",
				scale: 0.35,
			},
		},
		zhonghui: {
			潜蛟觊天: {
				name: "钟会/潜蛟觊天/XingXiang",
				scale: 0.35,
				x: [0,0.5],
				y: [0,0.5],
				beijing: {
					name: "钟会/潜蛟觊天/BeiJing",
					scale: 0.35,
					x: [0,0.98],
					y: [0,0.47],
				},
			},
			精炼策数: {
				name: "钟会/精炼策数/daiji2",
				scale: 0.35,
				x: [0,0.5],
				y: [0,0.5],
				shizhounian: true,
				background: "钟会/精炼策数/static_bg.png",
				beijing: {
					name: "钟会/精炼策数/beijing",
					scale: 0.35,
					x: [0,0.98],
					y: [0,0.47],
				},
				chuchang: {
					name: "钟会/精炼策数/chuchang",
					scale: 0.7,
				},
			},
			蒲月念兔: {
				name: "钟会/蒲月念兔/xingxiang",
				scale: 0.35,
				version: "4.0",
				x: [0,0.5],
				y: [0,0.5],
				beijing: {
					name: "钟会/蒲月念兔/beijing",
					scale: 0.35,
					version: "4.0",
					x: [0,0.98],
					y: [0,0.47],
				},
			},
			谋谟之勋: {
				name: "钟会/谋谟之勋/XingXiang",
				scale: 0.35,
				x: [0,0.5],
				y: [0,0.5],
				beijing: {
					name: "钟会/谋谟之勋/BeiJing",
					scale: 0.35,
					x: [0,0.98],
					y: [0,0.47],
				},
			},
			钟桂香蒲: {
				name: "钟会/钟桂香蒲/daiji2",
				scale: 0.35,
				x: [0,0.5],
				y: [0,0.5],
				shizhounian: true,
				background: "钟会/钟桂香蒲/static_bg.png",
				beijing: {
					name: "钟会/钟桂香蒲/beijing",
					scale: 0.35,
					x: [0,0.98],
					y: [0,0.47],
				},
				chuchang: {
					name: "钟会/钟桂香蒲/chuchang",
					scale: 0.7,
				},
			},
			龙年端午: {
				name: "钟会/龙年端午/XingXiang",
				scale: 0.35,
				x: [0,0.5],
				y: [0,0.5],
				beijing: {
					name: "钟会/龙年端午/BeiJing",
					scale: 0.35,
					x: [0,0.98],
					y: [0,0.47],
				},
			},
		},
		shen_pangtong: {
			经典形象: {
				name: "神庞统/经典形象/daiji",
				scale: 0.35,
				version: "4.0",
				x: [0,0.5],
				y: [0,0.5],
				background: "神庞统/经典形象/static_bg.png",
			},
		},
	}

})
