import { Character } from "../../../../noname/library/element/index.js";
import { _status, get } from "../../../../noname.js";

const bool = _status.connectMode ? lib.configOL.jinEx : get.config("jinEx");

export default {
	gz_jun_jin_simayi: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		img:"mode/guozhan/src/image/gz_jun_jin_simayi.jpg",
		skills: ["gz_jiaping", "gz_guikuang", "gz_shujuan"],
	}),
	gz_simaliang: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_gongzhi", "gz_sheju"],
		img: "image/character/jsrg_simaliang.jpg",
	}),
	gz_wangjun: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_chengliu"],
		img: "image/character/jsrg_wangjun.jpg",
	}),
	gz_malong: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_zhuanzhan", "gz_xunji"],
		img: "image/character/jsrg_malong.jpg",
	}),
	gz_simalun: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		img:"mode/guozhan/src/image/gz_simalun.jpg",
		skills: ["gz_zhulan", "gz_luanchang"],
	}),
	gz_jin_guohuai: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gz_zhefu", "gz_yidu"],
	}),
	gz_wenyang: new Character({
		sex: "male",
		group: "jin",
		hp: 5,
		maxHp: 5,
		hujia: 0,
		skills: ["gz_duanqiu"],
		img:"mode/guozhan/src/image/gz_wenyang.jpg",
		hasSkinInGuozhan: true,
	}),
	gz_bailingyun: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		img:"mode/guozhan/src/image/gz_bailingyun.jpg",
		skills: ["gz_xiace", "gz_limeng"],
		hasSkinInGuozhan: true,
		names: "柏|灵筠",
	}),
	gz_sunxiuu: new Character({
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		img:"mode/guozhan/src/image/gz_sunxiuu.jpg",
		skills: ["gz_xiejian", "gz_yinsha"],
	}),
	gz_yangjun: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		img:"mode/guozhan/src/image/gz_yangjun.jpg",
		skills: ["gz_neiji"],
	}),
	gz_wangxiang: new Character({
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gz_bingxin"],
	}),
	gz_jin_zhangchunhua: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzhuishi", "fakeqingleng"],
	}),
	gz_new_jin_zhangchunhua: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gz_ejue", "gz_shangshi"],
		img:"mode/guozhan/src/image/gz_new_jin_zhangchunhua.jpg",
		dieAudios: ["jin_zhangchunhua"],
	}),
	gz_jin_simayi: new Character({
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakequanbian", "smyyingshi", "fakezhouting"],
	}),
	gz_new_jin_simayi: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_yingshi", "gz_shunfu"],
		junName: "gz_jun_jin_simayi",
		img:"mode/guozhan/src/image/gz_new_jin_simayi.jpg",
		dieAudios: ["jin_simayi"],
	}),
	gz_jin_wangyuanji: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gz_yanxi", "gz_shiren"],
	}),
	gz_jin_simazhao: new Character({
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gz_zhaoran", "gz_beiluan"],
	}),
	gz_jin_xiahouhui: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakebaoqie", "jyishi", "shiduo"],
	}),
	gz_jin_simashi: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp:  4,
		hujia: 0,
		skills:  ["gz_yimie", "gz_ruilve"],
	}),
	gz_duyu: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills:["gz_sanchen", "gz_pozhu"],
	}),
	gz_zhanghuyuechen: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_xijue", "gz_lvxian", "gz_yingwei"],
	}),
	gz_jin_yanghuiyu: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills:  ["gz_ciwei", "gz_caiyuan"],
	}),
	gz_simazhou: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills:  ["gz_pojing"],
	}),
	gz_shibao: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_zhuosheng"],
	}),
	gz_weiguan: new Character({
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills:  ["gz_chengxi", "gz_jiantong"],
	}),
	gz_zhongyan: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzbolan", "yifa"],
	}),
	gz_yangyan: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzxuanbei", "xianwan"],
	}),
	gz_zuofen: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzzhaosong", "gzlisi"],
	}),
	gz_xuangongzhu: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakeqimei", "ybzhuiji"],
	}),
	gz_xinchang: new Character({
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakecanmou", "congjian"],
	}),
	gz_yangzhi: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzwanyi", "gzmaihuo"],
	}),
	gz_jin_jiachong: new Character({
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills:  ["gz_chujue", "gz_jianzhi"],
	}),
	gz_jin_yanghu: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_huaiyuan", "gz_fushou"],
	}),
	gz_sp_duyu: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_wuku", "gz_miewu"],
	}),
	gz_pk_sp_duyu: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakezhufu"],
		dieAudios: ["sp_duyu"],
	}),
	gz_wangji: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakeqizhi", "fakejinqu"],
	}),

	///不臣篇晋章（自制）
	gz_jue_yangjun: new Character({
  sex: "male",
  group: "ye",
  hp: 4,
  maxHp: 4,
  hujia: 0,
  hasSkinInGuozhan: true,
  skills: ["gz_guishang","gz_niubi"],
  img:"mode/guozhan/src/image/gz_jue_yangjun.jpg",
  dieAudios: ["ext:侠道国战/audio/die/gz_jue_yangjun.mp3"],
}),

gz_jue_yangyan: new Character({
  sex: "female",
  group: "jin",
  hp: 3,
  maxHp: 3,
  hujia: 0,
  hasSkinInGuozhan: true,
  skills: ["gz_xianwan","gz_jiyuan"],
  img:"mode/guozhan/src/image/gz_jue_yangyan.jpg",
  dieAudios: ["ext:侠道国战/audio/die/gz_jue_yangyan.mp3"],
}),

gz_luji: new Character({
  sex: "male",
  group: "wu",
  hp: 3,
  maxHp: 3,
  hujia: 0,
  hasSkinInGuozhan: true,
  doubleGroup: ["jin","wu"],
  trashBin: [
    "des:陆机（261－303），字士衡，吴郡吴县（今江苏苏州）人，西晋文学家、书法家，孙吴丞相陆逊之孙、大司马陆抗之子，与其弟陆云合称“二陆”。孙吴灭亡后出仕晋朝司马氏政权，曾历任平原内史、祭酒、著作郎等职，世称“陆平原”。后死于“八王之乱”，被夷三族。他“少有奇才，文章冠世”（《晋书·陆机传》），与弟陆云俱为中国西晋时期著名文学家，被誉为“太康之英”。陆机还是一位杰出的书法家，他的《平复帖》是中国古代存世最早的名人书法真迹。"
  ],
  skills: ["gz_lingzhi","gz_ruluo"],
  img:"mode/guozhan/src/image/gz_luji.jpg",
  dieAudios: ["ext:侠道国战/audio/die/gz_luji.mp3"],
}),

gz_shantao: new Character({
  sex: "male",
  group: "jin",
  doubleGroup: ["jin","wei"],
  hp: 3,
  maxHp: 3,
  hujia: 0,
  hasSkinInGuozhan: true,
  trashBin: [
    "des:山涛（205年－283年3月3日），字巨源，河内郡怀县（今河南武陟西）人。三国至西晋时期官员、玄学家、名士，“竹林七贤”之一。[1][4]山涛早年家贫，喜好读《老子》《庄子》，因志同道合与嵇康、吕安、阮籍交好。他在四十岁时入仕，后因不愿卷入政党之争弃官归隐。"
  ],
  skills: ["gz_linzhe","gz_yamai"],
  img:"mode/guozhan/src/image/gz_shantao.jpg",
  dieAudios: ["ext:侠道国战/audio/die/gz_shantao.mp3"],
}),

gz_zhanghua: new Character({
  sex: "male",
  group: "jin",
  hp: 3,
  maxHp: 3,
  hujia: 0,
  hasSkinInGuozhan: true,
  doubleGroup: ["jin","wei"],
  skills: ["gz_juanzhi","gz_yinbing","gz_bihun"],
  img:"mode/guozhan/src/image/gz_zhanghua.jpg",
  dieAudios: ["ext:侠道国战/audio/die/gz_zhanghua.mp3"],
}),

gz_jiananfeng: new Character({
  sex: "female",
  group: "jin",
  hp: 3,
  maxHp: 3,
  hujia: 0,
  hasSkinInGuozhan: true,
  skills: ["gz_xugu","gz_xionglie"],
  img:"mode/guozhan/src/image/gz_jiananfeng.jpg",
  dieAudios: ["ext:侠道国战/audio/die/gz_jiananfeng.mp3"],
}),

gz_peixiu: new Character({
  sex: "male",
  group: "qun",
  hp: 3,
  maxHp: 3,
  hujia: 0,
  hasSkinInGuozhan: true,
  doubleGroup: ["jin","qun"],
  skills: ["gz_juezhi","gz_xingtu"],
  img:"mode/guozhan/src/image/gz_peixiu.jpg",
  dieAudios: ["ext:侠道国战/audio/die/gz_peixiu.mp3"],
}),

gz_zhugejing: new Character({
  sex: "male",
  group: "qun",
  hp: 4,
  maxHp: 4,
  hujia: 0,
  hasSkinInGuozhan: true,
  doubleGroup: ["jin","qun"],
  skills: ["gz_yanzuo","gz_pijian","gz_zeyu"],
  img:"mode/guozhan/src/image/gz_zhugejing.jpg",
  dieAudios: ["ext:侠道国战/audio/die/gz_zhugejing.mp3"],
}),

gz_qiaozhou: new Character({
  sex: "male",
  group: "shu",
  hp: 3,
  maxHp: 3,
  hujia: 0,
  hasSkinInGuozhan: true,
  doubleGroup: ["jin","shu"],
  skills: ["gz_baoguo","gz_yuandao","gz_yunxing"],
  img:"mode/guozhan/src/image/gz_qiaozhou.jpg",
  dieAudios: ["ext:侠道国战/audio/die/gz_qiaozhou.mp3"],
}),

gz_huoyi: new Character({
  sex: "male",
  group: "shu",
  hp: 4,
  maxHp: 4,
  hujia: 0,
  hasSkinInGuozhan: true,
  doubleGroup: ["jin","shu"],
  skills: ["gz_liefa"],
  img:"mode/guozhan/src/image/gz_huoyi.jpg",
  dieAudios: ["ext:侠道国战/audio/die/gz_huoyi.mp3"],
}),

gz_zhouchu: new Character({
  sex: "male",
  group: "wu",
  hp: 4,
  maxHp: 4,
  hujia: 0,
  hasSkinInGuozhan: true,
  doubleGroup: ["jin","wu"],
  skills: ["gz_xunfeng","gz_zhangming"],
  img:"mode/guozhan/src/image/gz_zhouchu.jpg",
  dieAudios: ["ext:侠道国战/audio/die/gz_zhouchu.mp3"],
}),

gz_jue_yangzhi: new Character({
  sex: "female",
  group: "jin",
  hp: 3,
  maxHp: 3,
  hujia: 0,
  skills: ["gz_yisang","gz_jiubo"],
  img:"mode/guozhan/src/image/gz_jue_yangzhi.jpg",
}),

gz_zhugezhan: new Character({
  sex: "male",
  group: "shu",
  hp: 4,
  maxHp: 4,
  hujia: 0,
  skills: ["gz_dishang","gz_zuilun"],
  img:"mode/guozhan/src/image/gz_zhugezhan.jpg",
}),

gz_zhanghuai: new Character({
  sex: "female",
  group: "wu",
  hp: 3,
  maxHp: 3,
  hujia: 0,
  skills: ["gz_laoyan","gz_jueyan"],
  img:"mode/guozhan/src/image/gz_zhanghuai.jpg",
}),

gz_xuncan: new Character({
  sex: "male",
  group: "wei",
  hp: 3,
  maxHp: 3,
  hujia: 0,
  skills: ["gz_yundao","gz_youming"],
  img:"mode/guozhan/src/image/gz_xuncan.jpg",
}),

gz_yuantan: new Character({
  sex: "male",
  group: "qun",
  hp: 4,
  maxHp: 4,
  hujia: 0,
  skills: ["gz_qiaosi","gz_baizu"],
  img:"mode/guozhan/src/image/gz_yuantan.jpg",
}),
};
