import { Character } from "../../../../noname/library/element/index.js";
import { _status, get } from "../../../../noname.js";

const bool = _status.connectMode ? lib.configOL.jinEx : get.config("jinEx");

export default {
	gz_jun_jin_simayi: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		img:"mode/guozhan/src/image/gz_jun_jin_simayi.jpg",
				dieAudios: ["huan_simayi"],
		skills: ["gz_jiaping", "gz_guikuang", "gz_shujuan"],
	}),
	gz_simaliang: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_gongzhi", "gz_sheju"],
  dieAudios: true,
		img: "image/character/jsrg_simaliang.jpg",
	}),
	gz_wangjun: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_chengliu"],
		img: "image/character/jsrg_wangjun.jpg",
	}),
	gz_malong: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_zhuanzhan", "gz_xunji"],
			dieAudios: ["jsrg_malong"],
		img: "image/character/jsrg_malong.jpg",

	}),
	gz_simalun: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		img:"mode/guozhan/src/image/gz_simalun.jpg",
		skills: ["gz_zhulan", "gz_luanchang"],
		  dieAudios: true,
	}),
	gz_jin_guohuai: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gz_zhefu", "gz_yidu"],
	}),
	gz_wenyang: new Character({
		sex: "male",
		group: "jin",
		hp: 5,
		maxHp: 5,
		hujia: 0,
		skills: ["gz_duanqiu"],
		img:"mode/guozhan/src/image/gz_wenyang.jpg",
		hasSkinInGuozhan: true,
	}),
	gz_bailingyun: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		img:"mode/guozhan/src/image/gz_bailingyun.jpg",
		skills: ["gz_xiace", "gz_limeng"],
		hasSkinInGuozhan: true,
		names: "柏|灵筠",
	}),
	gz_sunxiuu: new Character({
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		img:"mode/guozhan/src/image/gz_sunxiuu.jpg",
		  dieAudios: true,
		skills: ["gz_xiejian", "gz_yinsha"],
	}),
	gz_yangjun: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		img:"mode/guozhan/src/image/gz_yangjun.jpg",
		  dieAudios: true,
		skills: ["gz_neiji"],
	}),
	gz_wangxiang: new Character({
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gz_bingxin"],
	}),
	gz_jin_zhangchunhua: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzhuishi", "fakeqingleng"],
	}),
	gz_new_jin_zhangchunhua: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gz_ejue", "gz_shangshi"],
		img:"mode/guozhan/src/image/gz_new_jin_zhangchunhua.jpg",
		dieAudios: ["jin_zhangchunhua"],
	}),
	gz_jin_simayi: new Character({
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakequanbian", "smyyingshi", "fakezhouting"],
	}),
	gz_new_jin_simayi: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_yingshi", "gz_shunfu"],
		junName: "gz_jun_jin_simayi",
		img:"mode/guozhan/src/image/gz_new_jin_simayi.jpg",
		dieAudios: ["jin_simayi"],
	}),
	gz_jin_wangyuanji: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gz_yanxi", "gz_shiren"],
	}),
	gz_jin_simazhao: new Character({
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gz_zhaoran", "gz_beiluan"],
	}),
	gz_jin_xiahouhui: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakebaoqie", "jyishi", "shiduo"],
	}),
	gz_jin_simashi: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp:  4,
		hujia: 0,
		skills:  ["gz_yimie", "gz_ruilve"],
	}),
	gz_duyu: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills:["gz_sanchen", "gz_pozhu"],
	}),
	gz_zhanghuyuechen: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_xijue", "gz_lvxian", "gz_yingwei"],
	}),
	gz_jin_yanghuiyu: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills:  ["gz_ciwei", "gz_caiyuan"],
	}),
	gz_simazhou: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills:  ["gz_pojing"],
	}),
	gz_shibao: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_zhuosheng"],
	}),
	gz_weiguan: new Character({
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills:  ["gz_chengxi", "gz_jiantong"],
	}),
	gz_zhongyan: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzbolan", "yifa"],
	}),
	gz_yangyan: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzxuanbei", "xianwan"],
	}),
	gz_zuofen: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzzhaosong", "gzlisi"],
	}),
	gz_xuangongzhu: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakeqimei", "ybzhuiji"],
	}),
	gz_xinchang: new Character({
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakecanmou", "congjian"],
	}),
	gz_yangzhi: new Character({
		sex: "female",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["gzwanyi", "gzmaihuo"],
	}),
	gz_jin_jiachong: new Character({
		sex: "male",
		group: "jin",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills:  ["gz_chujue", "gz_jianzhi"],
	}),
	gz_jin_yanghu: new Character({
		sex: "male",
		group: "jin",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_huaiyuan", "gz_fushou"],
	}),
	gz_sp_duyu: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["gz_wuku", "gz_miewu"],
	}),
	gz_pk_sp_duyu: new Character({
		sex: "male",
		group: "qun",
		hp: 4,
		maxHp: 4,
		hujia: 0,
		skills: ["fakezhufu"],
		dieAudios: ["sp_duyu"],
	}),
	gz_wangji: new Character({
		sex: "male",
		group: "wei",
		hp: 3,
		maxHp: 3,
		hujia: 0,
		skills: ["fakeqizhi", "fakejinqu"],
	}),

	///不臣篇晋章（自制）
	gz_jue_yangjun: new Character({
  sex: "male",
  group: "ye",
  hp: 4,
  maxHp: 4,
  hujia: 0,
  hasSkinInGuozhan: true,
  skills: ["gz_guishang","gz_niubi"],
      dieAudios: ["gz_yangjun"],
  img:"mode/guozhan/src/image/gz_jue_yangjun.jpg",
}),

gz_jue_yangyan: new Character({
  sex: "female",
  group: "jin",
  hp: 3,
  maxHp: 3,
  hujia: 0,
  hasSkinInGuozhan: true,
  skills: ["gz_xianwan","gz_jiyuan"],
  img:"mode/guozhan/src/image/gz_jue_yangyan.jpg",
  dieAudios: ["yangyan"],
}),

gz_lujii: new Character({
  sex: "male",
  group: "wu",
  hp: 3,
  maxHp: 3,
  hujia: 0,
  hasSkinInGuozhan: true,
  doubleGroup: ["jin","wu"],
  trashBin: [
    "des:陆机（261－303），字士衡，吴郡吴县（今江苏苏州）人，西晋文学家、书法家，孙吴丞相陆逊之孙、大司马陆抗之子，与其弟陆云合称“二陆”。孙吴灭亡后出仕晋朝司马氏政权，曾历任平原内史、祭酒、著作郎等职，世称“陆平原”。后死于“八王之乱”，被夷三族。他“少有奇才，文章冠世”（《晋书·陆机传》），与弟陆云俱为中国西晋时期著名文学家，被誉为“太康之英”。陆机还是一位杰出的书法家，他的《平复帖》是中国古代存世最早的名人书法真迹。"
  ],
  skills: ["gz_lingzhi","gz_ruluo"],
  img:"mode/guozhan/src/image/gz_lujii.jpg",
    dieAudios: true,
}),

gz_shantao: new Character({
  sex: "male",
  group: "jin",
  doubleGroup: ["jin","wei"],
  hp: 3,
  maxHp: 3,
  hujia: 0,
  hasSkinInGuozhan: true,
  trashBin: [
    "des:山涛（205年－283年3月3日），字巨源，河内郡怀县（今河南武陟西）人。三国至西晋时期官员、玄学家、名士，“竹林七贤”之一。[1][4]山涛早年家贫，喜好读《老子》《庄子》，因志同道合与嵇康、吕安、阮籍交好。他在四十岁时入仕，后因不愿卷入政党之争弃官归隐。"
  ],
  skills: ["gz_linzhe","gz_yamai"],
  img:"mode/guozhan/src/image/gz_shantao.jpg",
  dieAudios: true,
}),

gz_zhanghua: new Character({
  sex: "male",
  group: "jin",
  hp: 4,
  maxHp: 4,
  hujia: 0,
  hasSkinInGuozhan: true,
  doubleGroup: ["jin","wei"],
  skills: ["gz_juanzhi","gz_yinbing"],
  img:"mode/guozhan/src/image/gz_zhanghua.jpg",
  dieAudios: ["zhanghua"],
}),

gz_jiananfeng: new Character({
  sex: "female",
  group: "jin",
  hp: 3,
  maxHp: 3,
  hujia: 0,
  hasSkinInGuozhan: true,
  skills: ["gz_xugu","gz_xionglie"],
  img:"mode/guozhan/src/image/gz_jiananfeng.jpg",
  dieAudios: ["jsrg_jiananfeng"],
}),

gz_peixiu: new Character({
  sex: "male",
  group: "qun",
  hp: 3,
  maxHp: 3,
  hujia: 0,
  hasSkinInGuozhan: true,
  doubleGroup: ["jin","qun"],
  skills: ["gz_juezhi","gz_xingtu"],
  img:"mode/guozhan/src/image/gz_peixiu.jpg",
  dieAudios: ["peixiu"],
}),

gz_zhugejing: new Character({
  sex: "male",
  group: "qun",
  hp: 4,
  maxHp: 4,
  hujia: 0,
  hasSkinInGuozhan: true,
  doubleGroup: ["jin","qun"],
  skills: ["gz_yanzuo","gz_pijian","gz_zeyu"],
  img:"mode/guozhan/src/image/gz_zhugejing.jpg",
  dieAudios: ["zhugejing"],
}),

gz_qiaozhou: new Character({
  sex: "male",
  group: "shu",
  hp: 3,
  maxHp: 3,
  hujia: 0,
  hasSkinInGuozhan: true,
  doubleGroup: ["jin","shu"],
  skills: ["gz_baoguo","gz_yuandao","gz_yunxing"],
  img:"mode/guozhan/src/image/gz_qiaozhou.jpg",
  dieAudios: ["qiaozhou"],
}),

gz_huoyi: new Character({
  sex: "male",
  group: "shu",
  hp: 4,
  maxHp: 4,
  hujia: 0,
      trashBin: [
    "des:  霍弋，字绍先，南郡枝江（今湖北省枝江市）人，三国时期蜀汉至西晋初时将领，蜀汉将领霍峻之子。刘备时为太子舍人。后主登基为谒者。诸葛亮北驻汉中时用为丞相府记室，诸葛亮死后为黄门侍郎，刘禅立太子后为中庶子。尽言规谏太子，甚为得体。后永昌郡蛮夷作乱，刘禅以霍弋领永昌太守，率军讨伐，斩其豪帅，郡界宁静之后迁监军翊军将军，领建宁太守，统南中诸郡。景耀六年（263年），进号安南将军。邓艾偷袭阴平，霍弋想率军救援成都，但刘禅以成都已有准备，不准，后刘禅投降，霍弋在得知司马氏善待刘禅后，方才率领南中六郡投降。降晋后仍为南中都督，平定交阯、日南、九真三郡，功封列侯。 "
  ],
  hasSkinInGuozhan: true,
  doubleGroup: ["jin","shu"],
  skills: ["gz_liefa"],
  img:"mode/guozhan/src/image/gz_huoyi.jpg",
  dieAudios: true,
}),

gz_zhouchu: new Character({
  sex: "male",
  group: "wu",
  hp: 4,
  maxHp: 4,
  hujia: 0,
  hasSkinInGuozhan: true,
  doubleGroup: ["jin","wu"],
  skills: ["gz_xunfeng","gz_zhangming"],
  img:"mode/guozhan/src/image/gz_zhouchu.jpg",
  dieAudios: ["jin_zhouchu"],
}),

gz_jue_yangzhi: new Character({
  sex: "female",
  group: "jin",
  hp: 3,
  maxHp: 3,
  hujia: 0,
  skills: ["gz_yisang","gz_jiubo"],
  		dieAudios: ["yangzhi"],
  img:"mode/guozhan/src/image/gz_jue_yangzhi.jpg",
}),

gz_zhugezhan: new Character({
  sex: "male",
  group: "shu",
  hp: 4,
  maxHp: 4,
  hujia: 0,
  skills: ["gz_dishang","gz_zuilun"],
  img:"mode/guozhan/src/image/gz_zhugezhan.jpg",
}),

gz_zhanghuai: new Character({
  sex: "female",
  group: "wu",
  hp: 3,
  maxHp: 3,
  hujia: 0,
  skills: ["gz_laoyan","gz_jueyan"],
  		dieAudios: ["zhanghuai"],
  img:"mode/guozhan/src/image/gz_zhanghuai.jpg",
}),

gz_xuncan: new Character({
  sex: "male",
  group: "wei",
  hp: 3,
  maxHp: 3,
  hujia: 0,
  skills: ["gz_yundao","gz_youming"],
  		dieAudios: ["clan_xuncan"],
  img:"mode/guozhan/src/image/gz_xuncan.jpg",
}),

gz_yuantan: new Character({
  sex: "male",
  group: "qun",
  hp: 4,
  maxHp: 4,
  hujia: 0,
  skills: ["gz_qiaosi","gz_baizu"],
  		dieAudios: ["tw_yuantan"],
  img:"mode/guozhan/src/image/gz_yuantan.jpg",
}),

gz_kuaishi: new Character({
                sex: "female",
                group: "jin",
                hp: 3,
                maxHp: 3,
                hujia: 0,
                skills: ["gz_hejue","gz_hexi"],
                trashBin: ["des:蒯夫人（？—？），三国荆州襄阳人。是魏国南阳太守蒯钧之女，其外祖父则是魏国重臣王肃，故蒯氏也是晋武帝的姨表妹。后于泰始年间嫁于孙秀为妻。  泰始六年（公元270年），吴国前将军孙秀投奔晋国，晋武帝厚待他，就任命孙秀为骠骑将军、交州牧、开府仪同三司，封会稽公，并将自己的表妹蒯氏许配给他，夫妻感情很好。  蒯夫人曾因为妒忌，故而辱骂孙秀为“貉子”，孙秀听后心中大为不平，于是从此不再进入内室。蒯夫人因而后悔自责，并向表兄晋武帝求救。恰好是时遇上武帝大赦天下，群臣都入朝觐见。朝见完毕，群臣都退下了，武帝却请孙秀单独留下，并从容说道：“天下旷荡，蒯夫人可得从其例不？”孙秀听后就解下头冠，向武帝谢罪。而蒯夫人与孙秀从此和好如初。"],
  img:"mode/guozhan/src/image/gz_kuaishi.jpg",
  dieAudios: true,
}),

gz_xuwen: new Character({
                sex: "female",
                group: "jin",
                hp: 3,
                maxHp: 3,
                hujia: 0,
                skills: ["gz_fuhui","gz_mohua"],
                trashBin: ["des:徐妏，三国时期名将王濬之妻，丹青妙手徐邈之女。徐妏继承父学，尤擅丹青之道，作画甚至到了以假乱真的程度，还擅长调配色彩。"],
  img:"mode/guozhan/src/image/gz_xuwen.jpg",
  dieAudios: true,
}),

// ==================== 武将数据 ====================

// 夏侯氏
gz_xiahoushi: new Character({
    sex: "female",
    group: "shu",
    hp: 3,
    maxHp: 3,
    hujia: 0,
    skills: ["gz_qiaoshi", "gz_yanyu"],
    img: "mode/guozhan/src/image/gz_xiahoushi.jpg",
	dieAudios: true,
}),

// 王异
gz_wangyi: new Character({
    sex: "female",
    group: "wei",
    hp: 3,
    maxHp: 3,
    hujia: 0,
    skills: ["gz_zhenlie", "gz_miji"],
    img: "mode/guozhan/src/image/gz_wangyi.jpg",
	dieAudios: true,
}),

// 贺齐
gz_heqi: new Character({
    sex: "male",
    group: "wu",
    hp: 4,
    maxHp: 4,
    hujia: 0,
    skills: ["gz_junwei"],
    img: "mode/guozhan/src/image/gz_heqi.jpg",
	dieAudios: true,
}),

// 马良
gz_feng_maliang: new Character({
    sex: "male",
    group: "shu",
    hp: 3,
    maxHp: 3,
    hujia: 0,
    skills: ["gz_zicai", "gz_zhengmu"],
    img: "mode/guozhan/src/image/gz_feng_maliang.jpg",
	dieAudios: true,
}),

// 群黄月英
gz_feng_huangyueying: new Character({
    sex: "female",
    group: "qun",
    hp: 3,
    maxHp: 3,
    hujia: 0,
    skills: ["gz_ruxin", "gz_linglong"],
    img: "mode/guozhan/src/image/gz_feng_huangyueying.jpg",
			dieAudios: true,
}),
gz_renwan: new Character({
    sex: "female",
    group: "wei",
    hp: 3,
    maxHp: 3,
    hujia: 0,
    skills: ["gz_pizou", "gz_juansui"],
    img: "mode/guozhan/src/image/gz_renwan.jpg",
			dieAudios: true,
}),
gz_bulianshi: new Character({
    sex: "female",
    group: "wu",
    hp: 3,
    maxHp: 3,
    hujia: 0,
    skills: ["gz_anxu", "gz_zhuiyi"],
    img: "mode/guozhan/src/image/gz_bulianshi.jpg",
	dieAudios: true,
}),
gz_gongsunxiu: new Character({
    sex: "male",
    group: "qun",
    hp: 4,
    maxHp: 4,
    hujia: 0,
    skills: ["gz_niejiang", "gz_kuizhen"],
    img: "mode/guozhan/src/image/gz_gongsunxiu.jpg",
	dieAudios: true,
}),

gz_zhongli_xushu: new Character({
    sex: "male",
    group: "zhongli",
    hp: 4,
    maxHp: 4,
    hujia: 0,
    skills: ["gz_jiange","gz_yinyu"],
    img: "mode/guozhan/src/image/gz_zhongli_xushu.jpg",
	dieAudios: true,
}),

gz_zhongli_jiaxu: new Character({
    sex: "male",
    group: "zhongli",
    hp: 3,
    maxHp: 3,
    hujia: 0,
    skills: ["gz_qingshi","gz_shuge","gz_anshi"],
    img: "mode/guozhan/src/image/gz_zhongli_jiaxu.jpg",
	dieAudios: true,
}),

gz_zhongli_xushao: new Character({
    sex: "male",
    group: "zhongli",
    hp: 3,
    maxHp: 3,
    hujia: 0,
    skills: ["gz_yingmen","gz_pingjian"],
    img: "mode/guozhan/src/image/gz_zhongli_xushao.jpg",
	dieAudios: true,
}),

gz_zhongli_zhaoe: new Character({
    sex: "female",
    group: "zhongli",
    hp: 3,
    maxHp: 3,
    hujia: 0,
    skills: ["gz_yanshi","gz_xinren"],
    img: "mode/guozhan/src/image/gz_zhongli_zhaoe.jpg",
	dieAudios: true,
}),

gz_zhongli_lusu: new Character({
    sex: "male",
    group: "zhongli",
    hp: 3,
    maxHp: 3,
    hujia: 0,
    skills: ["gz_xiangkui","gz_yangming"],
    img: "mode/guozhan/src/image/gz_zhongli_lusu.jpg",
	dieAudios: true,
}),
};
