export default {
	gz_jun_jin_simayi: "君司马懿",
	gz_jun_jin_simayi_prefix: "君",
	gz_jin_jiachong: "贾充",
	gz_jin_yanghu: "羊祜",
	gz_sp_duyu: "杜预",
	gz_jin_guohuai: "郭槐",
	gz_wangjun: "王濬",
	gz_malong: "马隆",
	gz_simalun: "司马伦",
	gz_simaliang: "司马亮",
	gz_wangxiang: "王祥",
	gz_yangjun: "杨骏",
	gz_sunxiuu: "孙秀",
	gz_bailingyun: "柏灵筠",
	gz_wenyang: "文鸯",
	gz_pk_sp_duyu: "杜预",
	gz_pk_sp_duyu_ab: "应变杜预",
	"gz_zhugezhan": "诸葛瞻",
            "gz_zhanghuai": "张怀",
            "gz_xuncan": "荀粲",
            "gz_yuantan": "袁谭",
           
                        "gz_jue_yangjun": "杨骏",
            "gz_jue_yangyan": "杨艳",
            "gz_lujii": "陆机",
            "gz_shantao": "山涛",
            "gz_zhugejing": "诸葛京",
            "gz_zhouchu": "周处",
            "gz_peixiu": "裴秀",
            "gz_jiananfeng": "贾南风",
            "gz_zhanghua": "张华",
            "gz_huoyi": "霍弋",
            "gz_qiaozhou": "谯周",
                        "gz_jue_yangzhi": "杨芷",
						"gz_kuaishi":"蒯氏",
						"gz_xuwen":"徐妏",
						"gz_xiahoushi": "夏侯涓",
"gz_wangyi": "王异",
"gz_heqi": "贺齐",
"gz_feng_maliang": "马良",
"gz_feng_huangyueying": "黄月英",
            "weishilijichuban":"魏势力基础版",
            "shushilijichuban":"蜀势力基础版",
             "wushilijichuban":"吴势力基础版",
              "qunshilijichuban":"群势力基础版",
               "jinshilijichuban":"晋势力基础版",

               "buchenpianyexinjia":"不臣篇野心家",

            "fengsuiliaoyuan":"烽燧燎原",
};
